### ISSUE TITLE
subprocess call for send_linux is unnecessarily blocking

### ISSUE THREAD

**Issue by zocker-160** [YuriyLisovskiy/pynotifier#13]
the `send_linux` function uses `subprocess.call`

https://github.com/YuriyLisovskiy/pynotifier/blob/75b8845aca29fafe2833afa604d773c11134a42a/pynotifier/pynotifier.py#L91

According to the python source code this does call `p.wait()` internally which is a blocking operation and makes the usage of pynotifier in asyncio-loops difficult.

https://hg.python.org/cpython/file/005d0678f93c/Lib/subprocess.py#l527

Would it be possible to just use `subprocess.Popen(command, shell=False)` (which is nonblocking) instead?

Thank you!

**Comment by YuriyLisovskiy** [comment]
Yes, please open a new pull request with desired improvements.

**Comment by zocker-160** [comment]
PR is up

**Comment by andy71** [comment]
I know this issue is old and closed, but I got some zombie processes of "notify-send" with these change. When I change it back to "subprocess.call(command)" it works fine for me. But I am not using asyncio, because I have never tried it. How did you solved it with asyncio and do you get some zombie processes?

**Comment by zocker-160** [comment]
This observation makes little sense, because as I linked above, when you look into the actual Python source code, `call()` does also use `Popen()` internally, just with the difference that it also calls `wait()` which is a blocking operation.

So if `Popen()` creates a zombie process, then `call()` does too and `wait()` should block indefinitely.

The only explanation I have is, that `wait()` is timing out, which will trigger a `kill()` and you ignore the resulting exception raised or `kill()` does not fully work and it gets stuck on the second `wait()` which does not have a timeout.

If that is the case, then you have to check what is going on with `notify-send`  and why it doesn't exit properly.

**Comment by andy71** [comment]
I am pretty sure that this doesn't make sense, but that's what I see here.
When I use the actual version `subprocess.Popen(command, shell=False)` I got every time a zombie process of notify-send.
When I change the actual version to this ... 
```
myprocess = subprocess.Popen(command, shell=False)
myprocess.wait()
```
... it works fine and there is never a zombie process.

That's the same behavior when I use the old version `subprocess.call(command)`, which also never produces a zombie process of notify-send.

I also tried to catch some exceptions at different places in my code and in the linux.py of pynotifier. With no result. I have not received an exception once.

I wrote also a small wrapper which replaced the original notify-send and captured exit code, stdout and stderr directly from the original binary. The process exits normally (0) and without any information on stdout and stderr. Whatever version I try, all looks the same.

That's the way how I use the Notification:
```
def send_notify(
	title,
	message,
	icon_path = '/usr/share/app-install/icons/mail-notification.svg',
	duration = 5,
	urgency = 'normal'):
	try:
		c = NotificationClient()
		c.register_backend(platform.Backend())
		notification = Notification(
			title = title,
			message = message,
			icon_path = icon_path,
			duration = duration,
			urgency = urgency
		)
		c.notify_all(notification)
	except Exception as e:
		SystemExit(e)
```

By the way, my aim is not to have your code changed again. I would like to adapt my code so that it no longer generates zombie processes.
